language: php
php:
  - 7.1
  - 7.4
  - 8.0
  - nightly
branches:
  only:
    - main
    - /^release\/.*$/
install:
  - composer install --ignore-platform-reqs=php
before_script:
  - php vendor/vimeo/psalm/psalm --clear-cache=true
script:
  - php vendor/bin/psalm
  - php $COMPOSER_BIN_DIR/phpunit ./tests
