language: php
php:
  - 7.1
  - 8.0
branches:
  only:
    - main
install:
  - composer install --ignore-platform-reqs
before_script:
  - php vendor/vimeo/psalm/psalm --clear-cache=true
script:
  - php vendor/bin/psalm
  - php vendor/bin/phpunit ./tests
